---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 1.0.5
  kernel_info:
    name: python3
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Climate Analysis and Exploration

##  Summary:
Hawaii had up to 6.5 inches of precipitation in the last twelve months. Average precipitation was 0.176. 
The minimum temperature reordered in Hawaii in the last year was 55 F, and the maximum was 90F. The aggregate weather data was used to compute daily normal for the intended trip during the year. 
Minimum, maximum, and average temperature during the trip were 62, 74, and 62 F respectively during the trip.

 Description of Data (what is sakila, where did you get it, what tables are in there)
2) Methodology (types of SQL queries used)
3) Broad summary of results/ SQL output
4) Conclusions/Final Thoughts
5) Limitations/Future data exploration ideas of Sakila (edited)


```{python}
# %matplotlib inline
from matplotlib import style
style.use('fivethirtyeight')
import matplotlib.pyplot as plt
```

```{python}
import numpy as np
import pandas as pd
```

```{python}

import datetime as dt
```

# Reflect Tables into SQLAlchemy ORM

```{python}
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
from sqlalchemy import create_engine, inspect
```

```{python}
#Creating engine 
engine = create_engine("sqlite:///Resources/hawaii.sqlite", echo=False)

```

```{python}
# reflecting an existing database into a new model
Base = automap_base()

# reflecting the tables
Base.prepare(engine, reflect=True)
```

```{python}
# reflect an existing database into a new model
Base = automap_base()

# reflect the tables
Base.prepare(engine, reflect=True)# We can view all of the classes that automap found
Base.classes.keys()
```

```{python}
# Save references to each table
Measurement = Base.classes.measurement
Station = Base.classes.station
```

```{python}
# Create our session (link) from Python to the DB
session = Session(engine)
```

```{python}
#Enables to know what in each each tables
inspector = inspect(engine)
inspector.get_table_names()
```

```{python}
from sqlalchemy import create_engine, inspect, MetaData,Table
from sqlalchemy.engine.reflection import Inspector
```

```{python}
metadata = MetaData()
```

```{python}
inspector = inspect(engine)
inspector.get_table_names()
```

```{python}
meta = MetaData()
user_table = Table('measurement', meta)
insp = Inspector.from_engine(engine)
insp.reflecttable(user_table, None)
```

```{python}
insp.get_columns('measurement')
```

```{python}
insp.get_columns('station')
```

```{python}
columns = inspector.get_columns("Measurement")
for c in columns:
    print(c["name"], c["type"])
```

```{python}
columns = inspector.get_columns("Station")
for c in columns:
    print(c["name"], c["type"])
```

# Exploratory Climate Analysis

```{python}
#Total dates
session.query(func.count(Measurement.date)).all()
```

```{python}
#Earliest date
first_date = session.query(Measurement.date).order_by(Measurement.date).first()
first_date
```

```{python}
#Last date date
last_date = session.query(Measurement.date).order_by(Measurement.date.desc()).first()
last_date
```

```{python}
engine.execute("SELECT * FROM Measurement LIMIT 5").fetchall()

```

```{python}
engine.execute("SELECT * FROM Station LIMIT 5").fetchall()

```

```{python}
one_year_ago = dt.date(2017,8,23) - dt.timedelta(days=365)
print(one_year_ago)
```

```{python}
# Design a query to retrieve the last 12 months of precipitation data and plot the results
results = session.query(Measurement.date, Measurement.prcp).filter(Measurement.date > one_year_ago).all()
results
```

```{python}
df = pd.DataFrame(results)
df.head()
```

```{python}
df2 = df.set_index("date")
df2.head()
```

```{python}
#fig = plt.figure(figsize=(200,100))
df.plot("date", "prcp")
#df.grid(True)
plt.xlabel("Date Range: (2016-08-23 to 2017-08-23)")
plt.ylabel("Percipitation Volume (Inches)")
plt.title("Precipitation Analysis")
plt.legend()
plt.tight_layout()
plt.show()

```

```{python}
# Use Pandas to calcualte the summary statistics for the precipitation data
df.describe()
```

```{python}
# Design a query to show how many stations are available in this dataset?
session.query(func.count(Station.station)).all()

```

```{python}
# First station
session.query(Station.station).order_by(Station.station.desc()).first()
```

```{python}
# Active Stations
Desc_active_stations = session.query(Measurement.station, func.count(Measurement.prcp)).\
                                     group_by(Measurement.station).order_by(func.count(Measurement.prcp).desc()).all()
Desc_active_stations
```

```{python}
#Most active Station 
Most_active_stations = session.query(Measurement.station).\
                                     group_by(Measurement.station).order_by(func.count(Measurement.prcp).desc()).\
                                     limit(1).scalar()
Most_active_stations
```

```{python}
# What are the most active stations? (i.e. what stations have the most rows)?
# List the stations and the counts in descending order.
Most_active_station = session.query(Measurement.station).\
                                     group_by(Measurement.station).order_by(func.count(Measurement.prcp).desc()).\
                                     limit(1).scalar()
Most_active_station

```

```{python}
# time of observation (TOBs)
tobs_results = session.query(Measurement.station, Measurement.tobs).filter(Measurement.date.between("2016.08.23", "2017.08.23")).all()
tobs_results
```

```{python}
# Using the station id from the previous query, calculate the lowest temperature recorded, 
# highest temperature recorded, and average temperature most active station?

temperature_intel = session.query(Measurement.station, Measurement.date, Measurement.tobs).\
    filter(Measurement.station == Most_active_station).\
    filter(Measurement.date.between("2016.08.23", "2017.08.23")).\
    order_by(Measurement.date).all()
temperature_intel
```

```{python}
# Choose the station with the highest number of temperature observations.
# Query the last 12 months of temperature observation data for this station and plot the results as a histogram
fig2 = plt.figure(figsize=(5,6))
plt.grid(True)
temp_intel_df = pd.DataFrame(temperature_intel)
plt.hist(temp_intel_df['tobs'])
bin_size = 12
plt.xlabel("Recorded Temperatures")
plt.ylabel("Freqency")
plt.title("Station with Highest Recorded Observations")
plt.legend()
plt.show()
 
```

```{python}
# This function called `calc_temps` will accept start date and end date in the format '%Y-%m-%d' 
# and return the minimum, average, and maximum temperatures for that range of dates
def calc_temps(start_date, end_date):
    """TMIN, TAVG, and TMAX for a list of dates.
    
    Args:
        start_date (string): A date string in the format %Y-%m-%d
        end_date (string): A date string in the format %Y-%m-%d
        
    Returns:
        TMIN, TAVE, and TMAX
    """
    
    return session.query(func.min(Measurement.tobs), func.avg(Measurement.tobs), func.max(Measurement.tobs)).\
        filter(Measurement.date >= start_date).filter(Measurement.date <= end_date).all()

# function usage example
print(calc_temps('2012-02-28', '2012-03-05'))



```

```{python}
# Use your previous function `calc_temps` to calculate the tmin, tavg, and tmax 
# for your trip using the previous year's data for those same dates.

Temp=[]
start_date='2012-02-28'
end_date='2012-03-05'
def calc_temps(start_date, end_date):
    results=session.query(func.max(Measurement.tobs).label("max_tobs"), \
                          func.min(Measurement.tobs).label("min_tobs"),\
                          func.avg(Measurement.tobs).label("avg_tobs")).\
                          filter(Measurement.date.between(start_date , end_date))  
    res = results.one()
    res
    TMax = res.max_tobs
    TMin= res.min_tobs
    TAvg= res.avg_tobs
    Temp.append(TMax)
    Temp.append(TMin)
    Temp.append(TAvg)
  
calc_temps(start_date, end_date)
Temp

```

```{python}
TAvg=Temp[2]
TMin=Temp[1]
TMax=Temp[0]
```

```{python}
plt.bar( 1,TAvg, color = 'green', yerr = TMax-TMin, align='center')
plt.xlim(-0.2, 2.2)
plt.ylim([0, 110])
plt.axes().get_xaxis().set_visible(False)
plt.title('Trip Avg Temp')
plt.ylabel("Temp (F)")
plt.tight_layout()
plt.show()
```

```{python}
# Calculate the total amount of rainfall per weather station for your trip dates using the previous year's matching dates.
# Sort this in descending order by precipitation amount and list the station, name, latitude, longitude, and elevation

Rainfall_results = session.query(Measurement.station, func.count(Measurement.prcp)).\
                   group_by(Measurement.station).filter(Measurement.date.between("2016.08.23", "2017.08.23")).all()
Rainfall_results

```

```{python}
def precipitation(start_date, end_date):
    
        # Docstring for the function `calc_temps`
    """Precipitation information per weather station
    
    Args:
        start_date (string): A date string in the format %Y-%m-%d
        end_date (string): A date string in the format %Y-%m-%d
        
    Returns:
        A list of tuples containing precipitation amount, station, name, latitude, longitude, and elevation in descending order.
    """
    
    sel = [Measurement.station, 
           Station.name, 
           Station.latitude, 
           Station.longitude, 
           Station.elevation, 
           Measurement.prcp]
    
    return session.query(*sel).\
            filter(Measurement.station == Station.station).filter(Measurement.date >= start_date).filter(Measurement.date <= end_date).group_by(Measurement.station).order_by(Measurement.prcp.desc()).all()

print(precipitation('2017-08-09','2017-08-23'))
```
